# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7860e0bc3c2fdaa00d0aca4e4293512d5a82afb7b27c8f0b60ece16ad10c52953653df5bbd0a8320cf0ea3e34e310adfa9e3a3c60735ea5bac196ae720f1b40f

test:
  secret_key_base: 3cfa108d07c9642a852b5498e8b70a854fd52f8e1beb9e74c5206ed144a8883a04dba4ecf7de986e06ee0f6a59fadb1c9322726ed5d542a3167a07d59649ee4c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
